### ISSUE TITLE
Advanced Search Engine (ElasticSearch)

### ISSUE THREAD

**Issue by xkidro** [EasyEngine/feature-requests#20]
It would be really nice if EE would include a better search engine for wordpress I was thinking of http://lucene.apache.org/solr/ with https://wordpress.org/plugins/wpsolr-search-engine/

But there are also others like http://sphinxsearch.com/ with https://wordpress.org/plugins/wordpress-sphinx-plugin/

**Comment by michacassola** [comment]
@espellcaste Please do not post +1 as @rahul286 asked us not to in the readme of this repo. Use the thumbs up response instead please.

**Comment by michacassola** [comment]
For a wordpress site one container should be enough I guess?

Do we need one container per site or can one container be used for several sites?
If we need several containers we need to map them to different ports.

Compose file example: (https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
```
version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch-$sitename
    environment:
      - cluster.name=docker-cluster-$sitename
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/$sitename/data
    ports:
      - 9200:9200

volumes:
  esdata1:
    driver: local
```
