### ISSUE TITLE
Support for KeyDB

### ISSUE THREAD

**Issue by dhsathiya** [EasyEngine/feature-requests#86]
**KeyDB:** _`KeyDB is a high performance fork of Redis with a focus on multithreading, memory efficiency, and high throughput. `_
https://docs.keydb.dev/docs/intro/

**Dockerfiles:** https://docs.keydb.dev/docs/dockerfiles/

Changes to be made (for testing)
File: `/opt/easyengine/services/docker-compose.yml`
```yml
...
  global-redis:                                                                                                                                                                                                     
    image: eqalpha/keydb
...
    command: ["keydb-server", "/etc/keydb/keydb.conf"]
...
```
